//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterPage.html_project.my_animal_website.the_site_code__html_.tables
{


    public partial class table
    {
    }
}
